-- BR-220 verify-email storage. Single-use, hash-only, append-only audit-friendly.
-- Tokens generated by Lambda (UUID v4 → SHA-256 hex), 24h TTL.

CREATE TABLE email_verifications (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id     UUID         NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  token_hash      TEXT         NOT NULL,
  expires_at      TIMESTAMPTZ  NOT NULL,
  consumed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX email_verifications_token_hash_key
  ON email_verifications (token_hash);

CREATE INDEX email_verifications_customer_id_consumed_idx
  ON email_verifications (customer_id) WHERE consumed_at IS NULL;

ALTER TABLE email_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_verifications FORCE ROW LEVEL SECURITY;

CREATE POLICY email_verifications_select_self
  ON email_verifications FOR SELECT
  USING (
    is_admin_role()
    OR customer_id = current_customer_id()
  );

CREATE POLICY email_verifications_insert_admin
  ON email_verifications FOR INSERT
  WITH CHECK (is_admin_role());

CREATE POLICY email_verifications_update_admin
  ON email_verifications FOR UPDATE
  USING (is_admin_role())
  WITH CHECK (is_admin_role());

CREATE POLICY email_verifications_delete_admin
  ON email_verifications FOR DELETE
  USING (is_admin_role());

-- Customer email_verified column.
-- Existing customers (pilot Giuseppe + 3 demo) were created via tag-link
-- flow with implicit email trust. Backfill preserves current behavior.
ALTER TABLE customers
  ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;

UPDATE customers SET email_verified = true;
